// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKmrNWvOjGRXvfGW6UMbUoLCMnIVX-Ncc',
    appId: '1:437604116518:web:5cf28a3635284b4a289ee7',
    messagingSenderId: '437604116518',
    projectId: 'handyman-5b706',
    authDomain: 'handyman-5b706.firebaseapp.com',
    storageBucket: 'handyman-5b706.firebasestorage.app',
    measurementId: 'G-RRWSRRR70N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOVE1Oq6ByMG23I_D4dyoZiyYd3WzjNmg',
    appId: '1:437604116518:android:2ad30b4e7c82cabb289ee7',
    messagingSenderId: '437604116518',
    projectId: 'handyman-5b706',
    storageBucket: 'handyman-5b706.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoTxENFE_mO6bGuy-yi5IbT6eStmpzzpk',
    appId: '1:437604116518:ios:8892adc762a87d13289ee7',
    messagingSenderId: '437604116518',
    projectId: 'handyman-5b706',
    storageBucket: 'handyman-5b706.firebasestorage.app',
    iosBundleId: 'com.example.serviceLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoTxENFE_mO6bGuy-yi5IbT6eStmpzzpk',
    appId: '1:437604116518:ios:8892adc762a87d13289ee7',
    messagingSenderId: '437604116518',
    projectId: 'handyman-5b706',
    storageBucket: 'handyman-5b706.firebasestorage.app',
    iosBundleId: 'com.example.serviceLink',
  );

}